"""Dev tool: regenerate rare_gear_catalog.py from the game data files.

Reads baseitemtypes.json + itemclasses.json (extracted game data, see the
eb2-pickit-generator reference repo's data/ folder) and writes
rare_gear_catalog.py — the per-base catalog that powers the Rare Gear tab's
"Per-base" mode. Run after a new PoE2 league adds bases:

    python build_rare_gear_catalog.py [path-to-data-folder]

Not imported by the app; only its output rare_gear_catalog.py is.
"""
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

DEFAULT_DATA = (Path(__file__).resolve().parent.parent /
                "eb2-pickit-generator-master" / "eb2-pickit-generator-master" / "data")

# item-class name -> (family key, family label, has defence combos)
FAMILIES = {
    "Boots":          ("Boots",         "Boots",           True),
    "Gloves":         ("Gloves",        "Gloves",          True),
    "Helmets":        ("Helmets",       "Helmets",         True),
    "Body Armours":   ("BodyArmours",   "Body Armour",     True),
    "Shields":        ("Shields",       "Shields",         True),
    "Bucklers":       ("Bucklers",      "Bucklers",        True),
    "Foci":           ("Foci",          "Foci",            False),
    "Quivers":        ("Quivers",       "Quivers",         False),
    "Bows":           ("Bows",          "Bows",            False),
    "Crossbows":      ("Crossbows",     "Crossbows",       False),
    "Quarterstaves":  ("Quarterstaves", "Quarterstaves",   False),
    "Wands":          ("Wands",         "Wands",           False),
    "Sceptres":       ("Sceptres",      "Sceptres",        False),
    "Staves":         ("Staves",        "Staves",          False),
    "One Hand Maces": ("OneHandMaces",  "One Hand Maces",  False),
    "Two Hand Maces": ("TwoHandMaces",  "Two Hand Maces",  False),
    "Spears":         ("Spears",        "Spears",          False),
    "Flails":         ("Flails",        "Flails",          False),
}

COMBO_KEYS = {
    "Str": "armour", "Dex": "evasion", "Int": "es",
    "StrDex": "armour_evasion", "StrInt": "armour_es", "DexInt": "evasion_es",
    "StrDexInt": "tri",
}

# Special/reward/unique-only bases that must not appear in pickit rules.
SKIP_ID = re.compile(r"Demigod|Wreath|Unique|Timeless|Radius|Lake|Breach|Delirium")

ID_RE = re.compile(
    r"^Four\w*?"
    r"(StrDexInt|StrDex|StrInt|DexInt|Str|Dex|Int)?"
    r"(?:Base)?(?:\d+)?(?:[a-c])?"
    r"(Cruel|Endgame)?$")


def bracket_of(marker, drop_level):
    if marker == "Endgame" or drop_level >= 65:
        return "high"
    if marker == "Cruel" or drop_level >= 45:
        return "mid"
    return "low"


def main():
    data_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_DATA
    if not (data_dir / "baseitemtypes.json").is_file():
        sys.exit(f"Game data not found: {data_dir / 'baseitemtypes.json'}\n"
                 f"Usage: python {Path(__file__).name} <path-to-data-folder>\n"
                 f"(the folder must contain baseitemtypes.json and itemclasses.json)")
    bases = json.loads((data_dir / "baseitemtypes.json").read_text(encoding="utf-8"))
    classes = json.loads((data_dir / "itemclasses.json").read_text(encoding="utf-8"))
    class_name = {c["_rid"]: c["Name"] for c in classes}

    # family -> combo -> bracket -> {name: drop_level}
    cat = defaultdict(lambda: defaultdict(lambda: {"low": {}, "mid": {}, "high": {}}))
    for b in bases:
        cls = class_name.get(b["ItemClass"])
        fam = FAMILIES.get(cls)
        if not fam or not b.get("Name"):
            continue
        seg = b["Id"].rsplit("/", 1)[-1]
        if SKIP_ID.search(seg):
            continue
        m = ID_RE.match(seg)
        if not m:
            continue
        fam_key, _label, has_combos = fam
        combo = COMBO_KEYS.get(m.group(1) or "", "all") if has_combos else "all"
        br = bracket_of(m.group(2), b.get("DropLevel", 1))
        pool = cat[fam_key][combo][br]
        # duplicate names (skill variants a/b/c) — keep one entry, highest drop
        if b["Name"] not in pool or b["DropLevel"] > pool[b["Name"]]:
            pool[b["Name"]] = b["DropLevel"]

    # The game reuses display names across distinct items (e.g. "Ornate Buckler"
    # drops at 52 and again as an Endgame base). [Type] rules match by name only,
    # so keep each name in its highest bracket — otherwise a looser low/mid rule
    # would silently override the user's stricter endgame tuning for the name.
    for combos in cat.values():
        for brackets in combos.values():
            for hi, lo in (("high", "mid"), ("high", "low"), ("mid", "low")):
                for name in brackets[hi]:
                    brackets[lo].pop(name, None)

    lines = [
        '"""Per-base Rare Gear catalog — GENERATED by build_rare_gear_catalog.py.',
        "",
        "Do not edit by hand; re-run the script after a league adds new bases.",
        "CATALOG[family][combo][bracket] = [base type names] (drop-level order).",
        '"""',
        "",
        "CATALOG = {",
    ]
    for _cls, (fam_key, _label, _hc) in FAMILIES.items():
        combos = cat.get(fam_key)
        if not combos:
            continue
        lines.append(f'    "{fam_key}": {{')
        for combo in ("armour", "evasion", "es", "armour_evasion",
                      "armour_es", "evasion_es", "tri", "all"):
            brackets = combos.get(combo)
            if not brackets:
                continue
            lines.append(f'        "{combo}": {{')
            for br in ("low", "mid", "high"):
                names = sorted(brackets[br], key=lambda n: (brackets[br][n], n))
                lines.append(f'            "{br}": {names!r},')
            lines.append("        },")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append(f'FAMILY_LABELS = { {v[0]: v[1] for v in FAMILIES.values()}!r}')
    lines.append("")

    # Amulets/Belts: flat base lists (no defence combos / brackets — the pro tab
    # gives them archetype cards instead). League bases (Lake/Delirium/Demigods
    # variants like Dusk Amulet or Golden Obi) are real drops — keep them.
    flat_skip = re.compile(r"Unique|Timeless|Breach|Base$")
    for cls, const in (("Amulets", "AMULET_BASES"), ("Belts", "BELT_BASES"),
                       ("Rings", "RING_BASES")):
        pool: dict = {}
        for b in bases:
            if class_name.get(b["ItemClass"]) != cls or not b.get("Name"):
                continue
            if flat_skip.search(b["Id"].rsplit("/", 1)[-1]):
                continue
            if b["Name"] not in pool or b["DropLevel"] > pool[b["Name"]]:
                pool[b["Name"]] = b["DropLevel"]
        names = sorted(pool, key=lambda n: (pool[n], n))
        lines.append(f"{const} = {names!r}")
        lines.append("")

    out = Path(__file__).resolve().parent / "rare_gear_catalog.py"
    out.write_text("\n".join(lines), encoding="utf-8")
    n_bases = sum(len(pool) for f in cat.values() for c in f.values() for pool in c.values())
    print(f"Wrote {out.name}: {len(cat)} families, {n_bases} bases")

    # A (family, combo) pair without a weight template is silently dropped by
    # both the UI and the emitter — warn so new-league additions aren't missed.
    try:
        import rare_gear_templates as rgt
        missing = [(f, c) for f, combos in cat.items() for c in combos
                   if not rgt.get_template(f, c)]
        if missing:
            print("WARNING — no template (add to rare_gear_templates.py):",
                  ", ".join(f"{f}/{c}" for f, c in missing))
    except Exception as e:  # templates import needs the app's deps
        print(f"(template-coverage check skipped: {e})")


if __name__ == "__main__":
    main()
