"""Per-base Rare Gear catalog — GENERATED by build_rare_gear_catalog.py.

Do not edit by hand; re-run the script after a league adds new bases.
CATALOG[family][combo][bracket] = [base type names] (drop-level order).
"""

CATALOG = {
    "Boots": {
        "armour": {
            "low": ['Rough Greaves', 'Iron Greaves', 'Bronze Greaves', 'Trimmed Greaves', 'Stone Greaves'],
            "mid": ['Plated Greaves', 'Reefsteel Greaves', 'Lionheart Greaves', 'Monument Greaves', 'Elegant Greaves', 'Carved Greaves'],
            "high": ['Bulwark Greaves', 'Totemic Greaves', 'Ornate Greaves', 'Vaal Greaves', 'Tasalian Greaves'],
        },
        "evasion": {
            "low": ['Rawhide Boots', 'Laced Boots', 'Embossed Boots', 'Steeltoe Boots', 'Lizardscale Boots'],
            "mid": ['Bound Boots', 'Flared Boots', 'Sleek Boots', 'Leatherplate Boots', 'Studded Boots', 'Serpentscale Boots'],
            "high": ['Cinched Boots', 'Embroidered Boots', 'Cavalry Boots', 'Dragonscale Boots', 'Drakeskin Boots'],
        },
        "es": {
            "low": ['Straw Sandals', 'Wrapped Sandals', 'Lattice Sandals', 'Silk Slippers', 'Feathered Sandals'],
            "mid": ['Flax Sandals', 'Laced Sandals', 'Bangled Sandals', 'Studded Sandals', 'Elegant Slippers', 'Dunerunner Sandals'],
            "high": ['Bound Sandals', 'Elaborate Sandals', 'Luxurious Slippers', 'Sandsworn Sandals', 'Sekhema Sandals'],
        },
        "armour_evasion": {
            "low": ['Mail Sabatons', 'Braced Sabatons', 'Stacked Sabatons'],
            "mid": ['Covered Sabatons', 'Soldiering Sabatons', 'Goldwork Sabatons', 'Flexile Sabatons', 'Bastion Sabatons'],
            "high": ['Bold Sabatons', 'Veteran Sabatons', 'Noble Sabatons', 'Fortress Sabatons', 'Blacksteel Sabatons'],
        },
        "armour_es": {
            "low": ['Padded Leggings', 'Secured Leggings', 'Pelt Leggings'],
            "mid": ['Adherent Leggings', 'Weaver Leggings', 'Bound Leggings', 'Gilt Leggings', 'Shamanistic Leggings'],
            "high": ['Faithful Leggings', 'Pious Leggings', 'Apostle Leggings', 'Warlock Leggings', 'Cryptic Leggings'],
        },
        "evasion_es": {
            "low": ['Frayed Shoes', 'Threaded Shoes', 'Hunting Shoes'],
            "mid": ['Steelpoint Shoes', 'Wayfarer Shoes', 'Silverbuckled Shoes', 'Velour Shoes', 'Treerunner Shoes'],
            "high": ['Bladed Shoes', 'Wanderer Shoes', 'Charmed Shoes', 'Quickslip Shoes', 'Daggerfoot Shoes'],
        },
        "tri": {
            "low": [],
            "mid": [],
            "high": ['Grand Cuisses'],
        },
    },
    "Gloves": {
        "armour": {
            "low": ['Stocky Mitts', 'Riveted Mitts', 'Tempered Mitts', 'Bolstered Mitts', 'Moulded Mitts'],
            "mid": ['Detailed Mitts', 'Plated Mitts', 'Elegant Mitts', 'Titan Mitts', 'Ancient Mitts', 'Feathered Mitts'],
            "high": ['Grand Mitts', 'Knightly Mitts', 'Ornate Mitts', 'Vaal Mitts', 'Massive Mitts'],
        },
        "evasion": {
            "low": ['Suede Bracers', 'Firm Bracers', 'Bound Bracers', 'Sectioned Bracers', 'Spined Bracers'],
            "mid": ['Fine Bracers', 'Hunting Bracers', 'Swift Bracers', 'Hardened Bracers', 'Refined Bracers', 'Spiked Bracers'],
            "high": ['Engraved Bracers', 'Stalking Bracers', 'Grand Bracers', 'Barbed Bracers', 'Polished Bracers'],
        },
        "es": {
            "low": ['Torn Gloves', 'Sombre Gloves', 'Stitched Gloves', 'Jewelled Gloves', 'Intricate Gloves'],
            "mid": ['Ominous Gloves', 'Pauascale Gloves', 'Embellished Gloves', 'Embroidered Gloves', 'Baroque Gloves', 'Gold Gloves'],
            "high": ['Adorned Gloves', 'Grim Gloves', 'Opulent Gloves', 'Vaal Gloves', 'Sirenscale Gloves'],
        },
        "armour_evasion": {
            "low": ['Ringmail Gauntlets', 'Layered Gauntlets', 'Doubled Gauntlets'],
            "mid": ['Ironmail Gauntlets', 'Plate Gauntlets', 'Captain Gauntlets', 'Burnished Gauntlets', 'Zealot Gauntlets'],
            "high": ['Ornate Gauntlets', 'Steelmail Gauntlets', 'Commander Gauntlets', 'Cultist Gauntlets', 'Blacksteel Gauntlets'],
        },
        "armour_es": {
            "low": ['Rope Cuffs', 'Aged Cuffs', 'Goldcast Cuffs'],
            "mid": ['Braided Cuffs', 'Verisium Cuffs', 'Heirloom Cuffs', 'Righteous Cuffs', 'Ornate Cuffs'],
            "high": ['Bound Cuffs', 'Signet Cuffs', 'Ancient Cuffs', 'Gleaming Cuffs', 'Adherent Cuffs'],
        },
        "evasion_es": {
            "low": ['Gauze Wraps', 'Linen Wraps', 'Spiral Wraps'],
            "mid": ['Bandage Wraps', 'Buckled Wraps', 'Cambric Wraps', 'Furtive Wraps', 'Adorned Wraps'],
            "high": ['Utility Wraps', 'War Wraps', 'Elegant Wraps', 'Vaal Wraps', 'Secured Wraps'],
        },
        "tri": {
            "low": [],
            "mid": [],
            "high": ['Grand Manchettes'],
        },
    },
    "Helmets": {
        "armour": {
            "low": ['Rusted Greathelm', 'Soldier Greathelm', 'Wrapped Greathelm', 'Spired Greathelm', 'Elite Greathelm', 'Warrior Greathelm'],
            "mid": ['Commander Greathelm', 'Corroded Greathelm', 'Mercenary Greathelm', 'Fierce Greathelm', 'Homeguard Greathelm', 'Sentinel Greathelm', 'Elegant Greathelm', 'Goliath Greathelm', 'Noble Greathelm'],
            "high": ['Guardian Greathelm', 'Warmonger Greathelm', 'Masked Greathelm', 'Paragon Greathelm', 'Imperial Greathelm'],
        },
        "evasion": {
            "low": ['Shabby Hood', 'Felt Cap', 'Lace Hood', 'Swathed Cap', 'Hunter Hood', 'Viper Cap'],
            "mid": ['Corsair Cap', 'Rotted Hood', 'Wool Cap', 'Leatherbound Hood', 'Narrow Hood', 'Velvet Cap', 'Wrapped Cap', 'Covert Hood', 'Deerstalker Hood'],
            "high": ['Armoured Cap', 'Woven Cap', 'Desert Cap', 'Trapper Hood', 'Freebooter Cap'],
        },
        "es": {
            "low": ['Twig Circlet', 'Wicker Tiara', 'Beaded Circlet', 'Chain Tiara', 'Feathered Tiara', 'Gold Circlet'],
            "mid": ['Druidic Circlet', 'Vermeil Circlet', 'Avian Tiara', 'Jade Tiara', 'Desert Circlet', 'Noble Circlet', 'Sandsworn Tiara', 'Twilight Tiara', 'Jungle Tiara'],
            "high": ['Magus Tiara', 'Skycrown Tiara', 'Sorcerous Tiara', 'Kamasan Tiara', 'Ancestral Tiara'],
        },
        "armour_evasion": {
            "low": ['Brimmed Helm', 'Guarded Helm', 'Visored Helm', 'Cowled Helm', 'Shielded Helm'],
            "mid": ['Closed Helm', 'Domed Helm', 'Engraved Helm', 'Soldier Helm', 'Decorated Helm', 'Cabalist Helm', 'Gladiatoral Helm'],
            "high": ['Gallant Helm', 'Warded Helm', 'Cryptic Helm', 'Champion Helm', 'Gladiatorial Helm'],
        },
        "armour_es": {
            "low": ['Iron Crown', 'Horned Crown', 'Cultist Crown', 'Martyr Crown', 'Heavy Crown'],
            "mid": ['Mailed Crown', 'Spiritbone Crown', 'Forest Crown', 'Zealot Crown', 'Lavish Crown', 'Hallowed Crown', 'Inquisitor Crown'],
            "high": ['Archon Crown', 'Druidic Crown', 'Saintly Crown', 'Divine Crown', 'Cryptic Crown'],
        },
        "evasion_es": {
            "low": ['Hewn Mask', 'Face Mask', 'Hooded Mask', 'Veiled Mask', 'Tribal Mask'],
            "mid": ['Oak Mask', 'Solid Mask', 'Bandit Mask', 'Skulking Mask', 'Shaded Mask', 'Pariah Mask', 'Avian Mask'],
            "high": ['Brigand Mask', 'Death Mask', 'Faridun Mask', 'Soaring Mask', 'Grinning Mask'],
        },
        "tri": {
            "low": [],
            "mid": [],
            "high": ['Grand Visage'],
        },
    },
    "BodyArmours": {
        "armour": {
            "low": ['Rusted Cuirass', 'Fur Plate', 'Iron Cuirass', 'Raider Plate', 'Maraketh Cuirass', 'Steel Plate', 'Full Plate', 'Vaal Cuirass'],
            "mid": ['Barbarian Plate', 'Juggernaut Plate', 'Rugged Cuirass', 'Chieftain Cuirass', 'Sandsworn Cuirass', 'Colosseum Plate', 'Elegant Plate', 'Champion Cuirass', 'Heavy Plate', 'Stone Cuirass'],
            "high": ['Glorious Plate', 'Soldier Cuirass', 'Conqueror Plate', 'Ornate Plate', 'Abyssal Cuirass', 'Utzaal Cuirass', 'Warlord Cuirass'],
        },
        "evasion": {
            "low": ['Leather Vest', 'Quilted Vest', 'Pathfinder Coat', 'Shrouded Vest', 'Rhoahide Coat', 'Studded Vest', "Scout's Vest", 'Serpentscale Coat'],
            "mid": ['Corsair Vest', 'Patchwork Vest', 'Hunting Coat', 'Riding Coat', 'Smuggler Coat', 'Strider Vest', 'Layered Vest', 'Hardleather Coat', 'Runner Vest', 'Lizardscale Coat'],
            "high": ['Exquisite Vest', 'Swiftstalker Coat', 'Mail Coat', 'Slipstrike Vest', 'Armoured Vest', 'Wyrmscale Coat', 'Corsair Coat'],
        },
        "es": {
            "low": ['Tattered Robe', 'Feathered Robe', "Hexer's Robe", 'Bone Raiment', 'Silk Robe', 'Keth Raiment', 'Votive Raiment', 'Altar Robe'],
            "mid": ['Avian Robe', 'Elementalist Robe', "Cursespeaker's Robe", 'Mystic Raiment', 'Luxurious Robe', 'Imperial Robe', 'River Raiment', 'Plated Raiment', "Adherent's Raiment", 'Ceremonial Robe'],
            "high": ['Havoc Raiment', 'Vile Robe', 'Enlightened Robe', 'Flowing Raiment', 'Arcane Raiment', 'Sacramental Robe', 'Feathered Raiment'],
        },
        "armour_evasion": {
            "low": ['Chain Mail', 'Rogue Armour', 'Vagabond Armour', 'Cloaked Mail', 'Explorer Armour', 'Scale Mail'],
            "mid": ['Knight Armour', 'Ring Mail', 'Scoundrel Armour', 'Ancestral Mail', 'Wanderer Armour', 'Lamellar Mail', 'Mantled Mail', 'Gladiator Armour', 'Trailblazer Armour', 'Golden Mail'],
            "high": ['Dastard Armour', 'Heroic Armour', 'Tournament Mail', 'Shrouded Mail', 'Slayer Armour', 'Death Mail', 'Thane Mail'],
        },
        "armour_es": {
            "low": ['Pilgrim Vestments', 'Pelt Mantle', 'Mail Vestments', 'Shaman Mantle', 'Ironclad Vestments', 'Sacrificial Mantle'],
            "mid": ['Cleric Vestments', 'Templar Vestments', 'Bearskin Mantle', 'Chain Vestments', 'Tideseer Mantle', 'Gilded Vestments', 'Occultist Mantle', 'Venerated Mantle', 'Plated Vestments', 'Heartcarver Mantle'],
            "high": ['Revered Vestments', 'Wolfskin Mantle', 'Corvus Mantle', 'Conjurer Mantle', 'Zenith Vestments', 'Death Mantle', 'Seastorm Mantle'],
        },
        "evasion_es": {
            "low": ['Hermit Garb', 'Waxed Jacket', 'Marabout Garb', 'Wayfarer Jacket', 'Anchorite Garb', "Scalper's Jacket"],
            "mid": ['Scoundrel Jacket', 'Oiled Jacket', 'Ascetic Garb', 'Evangelist Garb', 'Clandestine Jacket', 'Itinerant Jacket', 'Monastic Garb', 'Hatungo Garb', "Hawker's Jacket"],
            "high": ['Sleek Jacket', 'Torment Jacket', 'Devout Garb', 'Rambler Jacket', 'Assassin Garb', "Falconer's Jacket", 'Austere Garb'],
        },
        "tri": {
            "low": ['Garment'],
            "mid": [],
            "high": ['Grand Regalia'],
        },
    },
    "Shields": {
        "armour": {
            "low": ['Splintered Tower Shield', 'Painted Tower Shield', 'Braced Tower Shield', 'Barricade Tower Shield', 'Effigial Tower Shield', 'Rampart Tower Shield', 'Heraldric Tower Shield', 'Stone Tower Shield'],
            "mid": ['Aged Tower Shield', 'Crucible Tower Shield', 'Metalworked Tower Shield', 'Ancestor Tower Shield', 'Cultist Tower Shield', 'Phalanx Tower Shield', 'Bulwark Tower Shield', 'Defiant Tower Shield', 'Noble Tower Shield', 'Goldworked Tower Shield'],
            "high": ['Blacksteel Tower Shield', 'Royal Tower Shield', 'Fortress Tower Shield', 'Vaal Tower Shield', 'Tawhoan Tower Shield'],
        },
        "armour_evasion": {
            "low": ['Hardwood Targe', 'Pelage Targe', 'Studded Targe', 'Crescent Targe', 'Chiseled Targe', 'Feathered Targe'],
            "mid": ['Ironwood Targe', 'Stratified Targe', 'Fur-lined Targe', 'Carved Targe', 'Mercenary Targe', 'Mosaic Targe', 'Polished Targe', 'Aureate Targe', 'Stone Targe', 'Avian Targe'],
            "high": ['Grand Targe', 'Mammoth Targe', 'Baroque Targe', 'Soaring Targe', 'Golden Targe'],
        },
        "armour_es": {
            "low": ['Blazon Crest Shield', 'Sigil Crest Shield', 'Emblem Crest Shield', 'Jingling Crest Shield', 'Sectarian Crest Shield', 'Omen Crest Shield'],
            "mid": ['Painted Crest Shield', 'Wayward Crest Shield', 'Engraved Crest Shield', 'Seer Crest Shield', 'Descry Crest Shield', 'Stoic Crest Shield', 'Dekharan Crest Shield', 'Empyreal Crest Shield', 'Quartered Crest Shield', 'Glowering Crest Shield'],
            "high": ['Deified Crest Shield', 'Intricate Crest Shield', 'Sekheman Crest Shield', 'Vaal Crest Shield', 'Blacksteel Crest Shield'],
        },
    },
    "Bucklers": {
        "evasion": {
            "low": ['Leather Buckler', 'Wooden Buckler', 'Plated Buckler', 'Iron Buckler', 'Ridged Buckler', 'Spiked Buckler', 'Ringed Buckler', 'Edged Buckler'],
            "mid": ['Laminate Buckler', 'Oak Buckler', 'Painted Buckler', 'Pearl Buckler', 'Coiled Buckler', 'Spikeward Buckler', 'Array Buckler', 'Jingling Buckler', 'Bladeguard Buckler'],
            "high": ['Aegis Buckler', 'Ornate Buckler', 'Gutspike Buckler', 'Ancient Buckler', 'Desert Buckler'],
        },
    },
    "Foci": {
        "all": {
            "low": ['Twig Focus', 'Woven Focus', 'Antler Focus', 'Engraved Focus', 'Tonal Focus', 'Crystal Focus', 'Voodoo Focus', 'Plumed Focus'],
            "mid": ['Runed Focus', 'Wreath Focus', 'Staghorn Focus', 'Jingling Focus', 'Whorl Focus', 'Elegant Focus', 'Arrayed Focus', 'Attuned Focus', 'Cultist Focus', 'Hallowed Focus'],
            "high": ['Druidic Focus', 'Magus Focus', 'Leyline Focus', 'Sacred Focus', 'Tasalian Focus'],
        },
    },
    "Quivers": {
        "all": {
            "low": ['Broadhead Quiver', 'Fire Quiver', 'Sacral Quiver', 'Two-Point Quiver', 'Blunt Quiver', 'Toxic Quiver', 'Serrated Quiver'],
            "mid": ['Primed Quiver', 'Penetrating Quiver', 'Volant Quiver'],
            "high": ['Visceral Quiver'],
        },
    },
    "Bows": {
        "all": {
            "low": ['Crude Bow', 'Shortbow', 'Warden Bow', 'Recurve Bow', 'Composite Bow', 'Dualstring Bow', 'Cultist Bow', 'Zealot Bow'],
            "mid": ['Artillery Bow', 'Snakewood Shortbow', 'Protector Bow', 'Tribal Bow', 'Rider Bow', 'Greatbow', 'Twin Bow', 'Double Limb Bow', 'Adherent Bow', 'Militant Bow'],
            "high": ['Heavy Bow', 'Ironwood Shortbow', 'Cavalry Bow', 'Guardian Bow', 'Warmonger Bow', 'Gemini Bow', 'Obliterator Bow', 'Fanatic Bow'],
        },
    },
    "Crossbows": {
        "all": {
            "low": ['Makeshift Crossbow', 'Tense Crossbow', 'Sturdy Crossbow', 'Varnished Crossbow', 'Dyad Crossbow', 'Alloy Crossbow', 'Bombard Crossbow', 'Construct Crossbow'],
            "mid": ['Blackfire Crossbow', 'Taut Crossbow', 'Robust Crossbow', 'Piercing Crossbow', 'Painted Crossbow', 'Cumbrous Crossbow', 'Twin Crossbow', 'Dedalian Crossbow', 'Cannonade Crossbow', 'Bleak Crossbow'],
            "high": ['Esoteric Crossbow', 'Stout Crossbow', 'Engraved Crossbow', 'Desolate Crossbow', 'Flexed Crossbow', 'Elegant Crossbow', 'Gemini Crossbow', 'Siege Crossbow'],
        },
    },
    "Quarterstaves": {
        "all": {
            "low": ['Wrapped Quarterstaff', 'Long Quarterstaff', 'Gothic Quarterstaff', 'Crackling Quarterstaff', 'Crescent Quarterstaff', 'Steelpoint Quarterstaff', 'Slicing Quarterstaff', 'Barrier Quarterstaff'],
            "mid": ['Hefty Quarterstaff', 'Reaching Quarterstaff', 'Barbarous Quarterstaff', 'Smooth Quarterstaff', 'Arcing Quarterstaff', 'Anima Quarterstaff', 'Waxing Quarterstaff', 'Graceful Quarterstaff', 'Bladed Quarterstaff', 'Guardian Quarterstaff'],
            "high": ['Wyrm Quarterstaff', 'Sinister Quarterstaff', 'Lunar Quarterstaff', 'Razor Quarterstaff', 'Striking Quarterstaff', 'Bolting Quarterstaff', 'Dreaming Quarterstaff', 'Aegis Quarterstaff'],
        },
    },
    "Wands": {
        "all": {
            "low": ['Withered Wand', 'Attuned Wand', 'Bone Wand', 'Siphoning Wand', 'Volatile Wand', 'Galvanic Wand', 'Acrid Wand', 'Offering Wand'],
            "mid": ['Frigid Wand', 'Torture Wand', 'Critical Wand', 'Primordial Wand'],
            "high": ['Dueling Wand'],
        },
    },
    "Sceptres": {
        "all": {
            "low": ['Rattling Sceptre', 'Stoic Sceptre', 'Lupine Sceptre', 'Omen Sceptre', 'Ochre Sceptre', 'Shrine Sceptre', 'Devouring Sceptre', 'Clasped Sceptre'],
            "mid": ['Devotional Sceptre', 'Wrath Sceptre', 'Aromatic Sceptre', 'Pious Sceptre'],
            "high": ['Hallowed Sceptre'],
        },
    },
    "Staves": {
        "all": {
            "low": ['Ashen Staff', 'Gelid Staff', 'Voltaic Staff', 'Spriggan Staff', 'Pyrophyte Staff', 'Chiming Staff', 'Rending Staff', 'Reaping Staff'],
            "mid": ['Icicle Staff', 'Roaring Staff', 'Paralysing Staff', 'Sanctified Staff'],
            "high": ['Dark Staff', 'Ravenous Staff'],
        },
    },
    "OneHandMaces": {
        "all": {
            "low": ['Wooden Club', 'Smithing Hammer', 'Slim Mace', 'Spiked Club', 'Warpick', 'Plated Mace', 'Brigand Mace', 'Construct Hammer'],
            "mid": ['Calescent Hammer', 'Morning Star', 'Kalguuran Forgehammer', 'Flared Mace', 'Jade Club', 'Battle Pick', 'Lumen Mace', 'Marching Mace', 'Execratus Hammer', 'Bandit Mace', 'Structured Hammer'],
            "high": ['Torment Club', 'Flanged Mace', 'Crown Mace', 'Marauding Mace', 'Molten Hammer', 'Akoyan Club', 'Strife Pick', 'Fortified Hammer'],
        },
    },
    "TwoHandMaces": {
        "all": {
            "low": ['Felled Greatclub', 'Oak Greathammer', 'Forge Maul', 'Studded Greatclub', 'Cultist Greathammer', 'Temple Maul', 'Leaden Greathammer', 'Crumbling Maul'],
            "mid": ['Pointed Maul', 'Snakewood Greathammer', 'Blacksmith Maul', 'Totemic Greatclub', 'Zealot Greathammer', 'Greatmace', 'Precise Greathammer', 'Solemn Maul', 'Heavy Greathammer', 'Disintegrating Maul'],
            "high": ['Giant Maul', 'Anvil Maul', 'Sacred Maul', 'Ironwood Greathammer', 'Massive Greathammer', 'Fanatic Greathammer', 'Tawhoan Greatclub', 'Ruination Maul'],
        },
    },
    "Spears": {
        "all": {
            "low": ['Hardwood Spear', 'Ironhead Spear', 'Hunting Spear', 'Winged Spear', 'War Spear', 'Forked Spear', 'Barbed Spear', 'Broad Spear'],
            "mid": ['Crossblade Spear', 'Steelhead Spear', 'Coursing Spear', 'Seaglass Spear', 'Swift Spear', 'Sword Spear', 'Branched Spear', 'Striking Spear', 'Jagged Spear', 'Massive Spear'],
            "high": ['Helix Spear', 'Orichalcum Spear', 'Pronged Spear', 'Spiked Spear', 'Stalking Spear', 'Akoyan Spear', 'Flying Spear', 'Grand Spear'],
        },
    },
    "Flails": {
        "all": {
            "low": ['Splintered Flail', 'Chain Flail', 'Holy Flail', 'Iron Flail', 'Twin Flail', 'Slender Flail', 'Stone Flail', 'Ring Flail'],
            "mid": ['Guarded Flail', 'Icicle Flail', 'Tearing Flail', 'Great Flail'],
            "high": ['Abyssal Flail'],
        },
    },
}

FAMILY_LABELS = {'Boots': 'Boots', 'Gloves': 'Gloves', 'Helmets': 'Helmets', 'BodyArmours': 'Body Armour', 'Shields': 'Shields', 'Bucklers': 'Bucklers', 'Foci': 'Foci', 'Quivers': 'Quivers', 'Bows': 'Bows', 'Crossbows': 'Crossbows', 'Quarterstaves': 'Quarterstaves', 'Wands': 'Wands', 'Sceptres': 'Sceptres', 'Staves': 'Staves', 'OneHandMaces': 'One Hand Maces', 'TwoHandMaces': 'Two Hand Maces', 'Spears': 'Spears', 'Flails': 'Flails'}

AMULET_BASES = ['Azure Amulet', 'Crimson Amulet', 'Distorted Amulet', 'Dusk Amulet', 'Gloam Amulet', 'Penumbra Amulet', 'Tenebrous Amulet', 'Amber Amulet', 'Jade Amulet', 'Lapis Amulet', 'Pearlescent Amulet', 'Lunar Amulet', 'Bloodstone Amulet', 'Stellar Amulet', 'Solar Amulet', 'Gold Amulet']

BELT_BASES = ['Linen Belt', 'Rawhide Belt', 'Golden Obi', 'Wide Belt', 'Long Belt', 'Plate Belt', 'Ornate Belt', 'Mail Belt', 'Double Belt', 'Heavy Belt', 'Utility Belt', 'Fine Belt']

RING_BASES = ['Abyssal Signet', 'Dusk Ring', 'Gloam Ring', 'Iron Ring', 'Lazuli Ring', 'Penumbra Ring', 'Tenebrous Ring', 'Ruby Ring', 'Golden Hoop', 'Sapphire Ring', 'Topaz Ring', 'Amethyst Ring', 'Emerald Ring', 'Pearl Ring', 'Prismatic Ring', 'Gold Ring', 'Unset Ring']
